"""API Routers"""

from . import (
    admin_router,
    ai_settings_router,
    analytics_router,
    auth_router,
    bots_router,
    channels_router,
    client_errors_router,
    commands_router,
    crosshairs_router,
    discord_webhook_router,
    donation_router,
    events_router,
    game_queue_router,
    matcher_router,
    message_triggers_router,
    payment_config_router,
    releases_router,
    stats_router,
    timers_router,
    video_queue_router,
)

__all__ = [
    "admin_router",
    "ai_settings_router",
    "auth_router",
    "channels_router",
    "analytics_router",
    "commands_router",
    "crosshairs_router",
    "discord_webhook_router",
    "donation_router",
    "events_router",
    "game_queue_router",
    "matcher_router",
    "message_triggers_router",
    "payment_config_router",
    "releases_router",
    "stats_router",
    "timers_router",
    "bots_router",
    "client_errors_router",
    "video_queue_router",
]
