#!/usr/bin/env python3
"""Generate every env template + docs table + manifest from env.registry.toml.

    npm run nb -- env gen                 # or: npm run env:gen
    npm run nb -- env check               # verify on-disk == generated; exit 1 on drift
    python scripts/env/gen.py --print KEY # show where one variable lives

The registry (env.registry.toml at the repo root) is the single source of truth.
Generated files carry a "GENERATED" banner and must never be hand-edited.
"""

from __future__ import annotations

import json
import sys
import unicodedata
from dataclasses import dataclass, field
from pathlib import Path

import tomllib

ROOT = Path(__file__).resolve().parents[2]
REGISTRY = ROOT / "env.registry.toml"
MANIFEST = ROOT / "env.manifest.json"
DOCS = ROOT / "docs" / "guides" / "environment.md"

SEP_WIDTH = 80
GEN_BANNER = "# GENERATED by scripts/env/gen.py — do not edit; edit env.registry.toml"

# scope -> (relative example path, header lines after the banner, docs-table note)
RUNTIME_FILES: dict[str, tuple[str, list[str], str]] = {
    "root": (
        ".env.example",
        ["Root env template — copied to .env.dev, .env.stg, or .env.prod."],
        "Docker Compose 變數替換用。",
    ),
    "shared": (
        "backend/shared.env.example",
        ["Shared backend env template."],
        "api、twitch-bot、discord-bot 三服務共用。至少設一組 AI key；空的自動跳過。",
    ),
    "api": (
        "backend/api/.env.example",
        ["API service overrides."],
        "App 憑證走對應環境的 shared env。",
    ),
    "twitch": (
        "backend/twitch/.env.example",
        ["Twitch bot overrides."],
        "App 憑證與 `BOT_ID` / `OWNER_ID` 走對應環境的 shared env。",
    ),
    "discord": (
        "backend/discord/.env.example",
        ["Discord bot overrides."],
        "App 憑證走對應環境的 shared env。",
    ),
    "scrapling": (
        "backend/scrapling/.env.example",
        ["Scrapling sidecar (Threads OG proxy)."],
        "獨立 sidecar，不在 Compose stack 內；見 [integrations/scrapling.md](../integrations/scrapling.md)。",
    ),
    "frontend": (
        "frontend/.env.example",
        ["Frontend (Vite) — build-time only."],
        "build 時注入。Cloudflare Pages 另需在專案設定加 `API_BACKEND`（後端位址，由 Cloudflare Tunnel 提供）。",
    ),
}

GITHUB_FILES = {
    "secrets_base": ".github/secrets/base.env.example",
    "secrets_prod": ".github/secrets/prod.env.example",
    "secrets_stg": ".github/secrets/stg.env.example",
    "variables_base": ".github/variables/base.env.example",
    "variables_prod": ".github/variables/prod.env.example",
    "variables_stg": ".github/variables/stg.env.example",
}

# target -> (kind, env, header lines)
GITHUB_META: dict[str, tuple[str, str, list[str]]] = {
    "secrets_base": (
        "secrets",
        "base",
        ["GitHub Secrets — base (shared across all environments)."],
    ),
    "secrets_prod": (
        "secrets",
        "prod",
        ["GitHub Secrets — production (environment-specific, overrides base)."],
    ),
    "secrets_stg": (
        "secrets",
        "staging",
        ["GitHub Secrets — staging (environment-specific, overrides base)."],
    ),
    "variables_base": (
        "variables",
        "base",
        ["GitHub Variables — base (all-environment fallback)."],
    ),
    "variables_prod": (
        "variables",
        "prod",
        ["GitHub Variables — production (overrides base per-environment)."],
    ),
    "variables_stg": (
        "variables",
        "staging",
        ["GitHub Variables — staging (overrides base per-environment)."],
    ),
}

# The deploy workflow reads env.manifest.json via scripts/env/write_ci.sh —
# it no longer enumerates env keys, so there is nothing here to check against it.


@dataclass
class Var:
    key: str
    scopes: list[str]
    section: str = "App"
    description: str = ""
    default: str = ""
    commented: bool = False
    help: str = ""
    dev_hint: str = ""
    required: bool = False
    sensitive: bool = True
    name: str = ""
    ci: dict = field(default_factory=dict)
    ci_example: dict = field(default_factory=dict)

    @property
    def env_name(self) -> str:
        return self.name or self.key

    @property
    def ci_managed(self) -> bool:
        return bool(self.ci)

    @property
    def ci_file(self) -> str | None:
        return self.ci.get("file")

    @property
    def ci_source(self) -> str:
        return self.ci.get("source", "")

    @property
    def ci_scope(self) -> str:
        return self.ci.get("scope", "base")

    @property
    def ci_conditional(self) -> bool:
        return bool(self.ci.get("conditional", False))


def load_registry() -> tuple[list[Var], dict]:
    data = tomllib.loads(REGISTRY.read_text(encoding="utf-8"))
    meta = data.get("meta", {})
    vars_: list[Var] = []
    seen: set[str] = set()
    scoped_names: set[tuple[str, str]] = set()
    section_order = set(meta.get("section_order", []))
    for raw in data.get("var", []):
        v = Var(
            key=raw["key"],
            scopes=list(raw.get("scopes", [])),
            section=raw.get("section", "App"),
            description=raw.get("description", ""),
            default=str(raw.get("default", "")),
            commented=bool(raw.get("commented", False)),
            help=raw.get("help", ""),
            dev_hint=raw.get("dev_hint", ""),
            required=bool(raw.get("required", False)),
            sensitive=bool(raw.get("sensitive", True)),
            name=raw.get("name", ""),
            ci=raw.get("ci", {}),
            ci_example=raw.get("ci_example", {}),
        )
        if v.key in seen:
            sys.exit(f"registry error: duplicate key {v.key!r}")
        seen.add(v.key)
        unknown_scopes = set(v.scopes) - set(RUNTIME_FILES)
        if unknown_scopes:
            sys.exit(
                f"registry error: {v.key} has unknown scopes {sorted(unknown_scopes)}"
            )
        if v.section not in section_order:
            sys.exit(f"registry error: {v.key} has unknown section {v.section!r}")
        for scope in v.scopes:
            identity = (scope, v.env_name)
            if identity in scoped_names:
                sys.exit(
                    f"registry error: duplicate env name {v.env_name!r} in {scope}"
                )
            scoped_names.add(identity)
        if v.ci_managed:
            source_kind = v.ci_source.partition(":")[0]
            if source_kind not in {"secret", "var", "derived"}:
                sys.exit(
                    f"registry error: {v.key} has invalid CI source {v.ci_source!r}"
                )
            if v.ci_file and v.ci_file not in {
                "root",
                "shared",
                "api",
                "twitch",
                "discord",
            }:
                sys.exit(f"registry error: {v.key} has invalid CI file {v.ci_file!r}")
            if v.ci_scope not in {"base", "env"}:
                sys.exit(f"registry error: {v.key} has invalid CI scope {v.ci_scope!r}")
            if source_kind == "secret" and not v.sensitive:
                sys.exit(f"registry error: {v.key} is a secret but sensitive=false")
            if source_kind == "var" and v.sensitive:
                sys.exit(f"registry error: {v.key} is a variable but sensitive=true")
        unknown_examples = set(v.ci_example) - {"base", "prod", "staging"}
        if unknown_examples:
            sys.exit(
                f"registry error: {v.key} has unknown CI examples {sorted(unknown_examples)}"
            )
        vars_.append(v)
    return vars_, meta


# ── rendering helpers ───────────────────────────────────────────────────────


def sep(name: str) -> str:
    dashes = SEP_WIDTH - 5 - len(name) - 1
    return f"# ── {name} " + "─" * max(dashes, 3)


def render_line(v: Var, *, commented: bool) -> list[str]:
    out: list[str] = []
    if v.help:
        out.append(f"# {v.help}")
    prefix = "# " if commented else ""
    out.append(f"{prefix}{v.env_name}={v.default}")
    return out


def render_runtime_example(scope: str, vars_: list[Var], meta: dict) -> str:
    _rel, header, _note = RUNTIME_FILES[scope]
    mine = [v for v in vars_ if scope in v.scopes]
    order = meta["section_order"]

    body_sections: dict[str, list[Var]] = {}
    dev_vars: list[Var] = []
    for v in mine:
        if v.dev_hint:
            dev_vars.append(v)
        if v.section != "Dev":
            body_sections.setdefault(v.section, []).append(v)

    lines = [GEN_BANNER]
    for h in header:
        lines.append(f"# {h}")
    lines.append("# Create a runtime set with: npm run nb -- env init <dev|stg|prod>")
    lines.append("# Never commit runtime env files.")
    lines.append("")

    for section in order:
        if section == "Dev" or section not in body_sections:
            continue
        lines.append(sep(section))
        for v in body_sections[section]:
            lines += render_line(v, commented=v.commented)
        lines.append("")

    if dev_vars:
        lines.append(sep("Dev"))
        for v in dev_vars:
            if v.help:
                lines.append(f"# {v.help}")
            lines.append(f"# {v.dev_hint}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def github_targets(v: Var) -> list[str]:
    """Which .github/*.env.example files this var belongs in (by key set)."""
    if not v.ci_managed or not v.ci_source:
        return []
    if v.ci_source.startswith("derived:"):
        return []
    kind = "secrets" if v.ci_source.startswith("secret:") else "variables"
    if kind == "variables":
        if v.ci_scope == "base":
            return ["variables_base"]
        return ["variables_prod", "variables_stg"]
    if v.ci_scope == "base":
        return ["secrets_base"]
    return ["secrets_prod", "secrets_stg"]


def build_manifest(vars_: list[Var]) -> dict:
    files: dict[str, list[str]] = {}
    for scope, (rel, _h, _n) in RUNTIME_FILES.items():
        target = rel.replace(".example", "")
        files[target] = [v.env_name for v in vars_ if scope in v.scopes]

    ci: dict[str, dict] = {}
    for v in vars_:
        if not v.ci_managed:
            continue
        entry = {
            "source": v.ci_source,
            "scope": v.ci_scope,
            "conditional": v.ci_conditional,
        }
        if v.ci_file:
            entry["file"] = v.ci_file
        # var: sources pass GitHub Variables straight through; an unset one would
        # write an empty value, so carry the registry default as a fallback
        # (was `${{ vars.X || 'default' }}` in the old heredoc).
        if v.ci_source.startswith("var:") and not v.ci_conditional and v.default:
            entry["default"] = v.default
        ci[v.env_name] = entry

    return {
        "_generated_by": "scripts/env/gen.py",
        "runtime_files": files,
        "required_secrets": sorted(
            {
                v.env_name
                for v in vars_
                if v.required and v.ci_source.startswith("secret:")
            }
        ),
        "required_variables": sorted(
            {v.env_name for v in vars_ if v.required and v.ci_source.startswith("var:")}
        ),
        "ci": ci,
        "github_example_keys": _gh_keys(vars_),
    }


def render_github_example(target: str, vars_: list[Var], meta: dict) -> str:
    kind, env, header = GITHUB_META[target]
    rel = GITHUB_FILES[target].replace(".example", "")
    order = meta["section_order"]
    mine = [v for v in vars_ if target in github_targets(v)]

    lines = [GEN_BANNER]
    lines += [f"# {h}" for h in header]
    # Same sentence shape as the runtime templates so both read alike.
    target = rel.replace(".example", "")
    warn = " Never commit it." if kind == "secrets" else ""
    lines.append(f"# Copy to {target} and fill in values.{warn}")
    lines.append("")

    # .github files have no "Dev" concept — fold those vars into Monitoring.
    grouped: dict[str, list[Var]] = {}
    for v in mine:
        s = v.section if v.section in order else "App"
        if s == "Dev":
            s = "Monitoring"
        grouped.setdefault(s, []).append(v)

    for section in order:
        if section not in grouped:
            continue
        lines.append(sep(section))
        for v in grouped[section]:
            if v.help:
                lines.append(f"# {v.help}")
            if kind == "secrets":
                val = ""
            elif v.ci_example:
                val = v.ci_example.get(env, "")
            else:
                val = v.default
            lines.append(f"{v.env_name}={val}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


DOCS_BEGIN = "<!-- env:begin -->"
DOCS_END = "<!-- env:end -->"


def _display_width(value: str) -> int:
    """Return the terminal width Prettier uses when aligning Markdown tables."""
    return sum(
        0
        if unicodedata.combining(char)
        else 2
        if unicodedata.east_asian_width(char) in {"F", "W"}
        else 1
        for char in value
    )


def _render_markdown_table(rows: list[tuple[str, str]]) -> list[str]:
    widths = [
        max(3, max(_display_width(row[column]) for row in rows)) for column in range(2)
    ]

    def render_row(row: tuple[str, str]) -> str:
        cells = [
            value + " " * (widths[index] - _display_width(value))
            for index, value in enumerate(row)
        ]
        return f"| {cells[0]} | {cells[1]} |"

    return [
        render_row(rows[0]),
        f"| {'-' * widths[0]} | {'-' * widths[1]} |",
        *(render_row(row) for row in rows[1:]),
    ]


def render_docs_table(vars_: list[Var]) -> str:
    lines = [
        DOCS_BEGIN,
        "<!-- generated by scripts/env/gen.py — edit env.registry.toml -->",
    ]
    for scope, (rel, _h, note) in RUNTIME_FILES.items():
        target = rel.replace(".example", "")
        mine = [v for v in vars_ if scope in v.scopes]
        if not mine:
            continue
        lines.append("")
        lines.append(f"### `{target}`")
        lines.append("")
        if note:
            lines.append(note)
            lines.append("")
        rows = [("變數", "說明")]
        for v in sorted(mine, key=lambda x: x.env_name):
            desc = v.description.replace("|", "\\|") or "—"
            rows.append((f"`{v.env_name}`", desc))
        lines.extend(_render_markdown_table(rows))
    lines.append("")
    lines.append(DOCS_END)
    return "\n".join(lines)


# ── outputs ─────────────────────────────────────────────────────────────────


def generated_outputs() -> dict[Path, str]:
    vars_, meta = load_registry()
    out: dict[Path, str] = {}
    for scope in RUNTIME_FILES:
        rel = RUNTIME_FILES[scope][0]
        out[ROOT / rel] = render_runtime_example(scope, vars_, meta)
    for target, rel in GITHUB_FILES.items():
        out[ROOT / rel] = render_github_example(target, vars_, meta)
    out[MANIFEST] = (
        json.dumps(build_manifest(vars_), indent=2, ensure_ascii=False) + "\n"
    )
    return out


def splice_docs(vars_: list[Var]) -> str | None:
    if not DOCS.exists():
        return None
    lines = DOCS.read_text(encoding="utf-8").splitlines()
    block = render_docs_table(vars_)
    begins = [i for i, ln in enumerate(lines) if ln.strip() == DOCS_BEGIN]
    ends = [i for i, ln in enumerate(lines) if ln.strip() == DOCS_END]
    if begins and ends:
        pre = "\n".join(lines[: begins[0]])
        post = "\n".join(lines[ends[-1] + 1 :])
        return (pre + "\n" + block + "\n" + post).rstrip() + "\n"
    return (
        DOCS.read_text(encoding="utf-8").rstrip()
        + "\n\n## 變數對照（自動產生）\n\n"
        + block
        + "\n"
    )


def cmd_write() -> int:
    for path, content in generated_outputs().items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
        print(f"  wrote {path.relative_to(ROOT)}")
    vars_, _ = load_registry()
    spliced = splice_docs(vars_)
    if spliced is not None:
        DOCS.write_text(spliced, encoding="utf-8", newline="\n")
        print(f"  wrote {DOCS.relative_to(ROOT)} (env:begin..env:end block)")
    return 0


def cmd_check() -> int:
    drift: list[str] = []
    for path, content in generated_outputs().items():
        current = path.read_text(encoding="utf-8") if path.exists() else "<missing>"
        if current != content:
            drift.append(str(path.relative_to(ROOT)))

    vars_, _ = load_registry()

    # docs env:begin..env:end block
    spliced = splice_docs(vars_)
    if spliced is not None and DOCS.read_text(encoding="utf-8") != spliced:
        drift.append(str(DOCS.relative_to(ROOT)) + " (env block)")

    # .github/*.env.example are fully generated too (compared above via generated_outputs).
    # _deploy.yml reads env.manifest.json via scripts/env/write_ci.sh — it holds no
    # generated key list, so there is nothing to diff it against here.

    if drift:
        print("env drift — run `python scripts/env/gen.py`:")
        for d in drift:
            print(f"  - {d}")
        return 1
    print("env: registry, templates, docs and manifest are in sync.")
    return 0


def _gh_keys(vars_: list[Var]) -> dict[str, list[str]]:
    result: dict[str, list[str]] = {rel: [] for rel in GITHUB_FILES.values()}
    for v in vars_:
        for t in github_targets(v):
            result[GITHUB_FILES[t]].append(v.env_name)
    return {k: sorted(set(x)) for k, x in result.items()}


def cmd_print(key: str) -> int:
    vars_, _ = load_registry()
    for v in vars_:
        if key in (v.key, v.env_name):
            print(f"key         {v.key}")
            print(f"env name    {v.env_name}")
            print(f"scopes      {', '.join(v.scopes) or '(none — CI only)'}")
            print(
                f"files       {', '.join(RUNTIME_FILES[s][0].replace('.example', '') for s in v.scopes)}"
            )
            print(f"section     {v.section}")
            print(
                f"sensitive   {v.sensitive}  ({'secret' if v.sensitive else 'variable'})"
            )
            print(f"required    {v.required}")
            if v.ci_managed:
                print(
                    f"ci          file={v.ci_file} source={v.ci_source} scope={v.ci_scope} conditional={v.ci_conditional}"
                )
                print(
                    f"github      {', '.join(GITHUB_FILES[t] for t in github_targets(v)) or '(none)'}"
                )
            else:
                print("ci          (not CI-managed)")
            return 0
    print(f"{key!r} not found in registry")
    return 1


def main() -> int:
    args = sys.argv[1:]
    if not args:
        return cmd_write()
    if args[0] == "--check":
        return cmd_check()
    if args[0] == "--print" and len(args) == 2:
        return cmd_print(args[1])
    print(__doc__)
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
