"""OAuth helper functions — user find/create and account linking."""

import base64
import binascii
import hashlib
import hmac
import json
import logging
import secrets

from asyncpg import Pool
from asyncpg.exceptions import UniqueViolationError

logger = logging.getLogger(__name__)


async def find_or_create_user(
    pool: Pool,
    platform: str,
    platform_user_id: str,
    username: str,
    display_name: str | None = None,
    avatar: str | None = None,
) -> str:
    """Find existing user by linked account or create a new one.

    Uses a transaction to prevent TOCTOU race on concurrent OAuth callbacks.
    Returns users.id as string.
    """
    async with pool.acquire() as conn:
        # Fast path: linked account already exists (common case — no transaction needed)
        row = await conn.fetchrow(
            "SELECT user_id FROM user_linked_accounts"
            " WHERE platform = $1 AND platform_user_id = $2",
            platform,
            platform_user_id,
        )
        if row:
            return str(row["user_id"])

        # Slow path: create new user + linked account inside a transaction.
        # Under READ COMMITTED two concurrent OAuth callbacks can both pass the
        # fast-path check above. The UNIQUE constraint on user_linked_accounts
        # ensures only one INSERT wins; the loser catches UniqueViolationError
        # and falls back to a plain SELECT to return the winner's user_id.
        try:
            async with conn.transaction():
                user_row = await conn.fetchrow(
                    "INSERT INTO users (display_name, avatar) VALUES ($1, $2) RETURNING id",
                    display_name or username,
                    avatar,
                )
                user_id = str(user_row["id"])

                await conn.execute(
                    "INSERT INTO user_linked_accounts"
                    " (user_id, platform, platform_user_id, username)"
                    " VALUES ($1, $2, $3, $4)",
                    user_row["id"],
                    platform,
                    platform_user_id,
                    username,
                )
        except UniqueViolationError:
            # A concurrent request won the race — fetch the winner's user_id
            row = await conn.fetchrow(
                "SELECT user_id FROM user_linked_accounts"
                " WHERE platform = $1 AND platform_user_id = $2",
                platform,
                platform_user_id,
            )
            if row is None:
                raise RuntimeError(
                    f"Concurrent OAuth race for {platform}:{platform_user_id} — "
                    "winner's account disappeared before fallback SELECT"
                ) from None
            return str(row["user_id"])

    logger.info(f"Created user {user_id} for {platform}:{platform_user_id} ({username})")
    return user_id


# ---------------------------------------------------------------------------
# OAuth state encoding with HMAC-SHA256 CSRF protection
# ---------------------------------------------------------------------------


def _hmac_sign(data: dict, secret: str) -> str:
    """Return HMAC-SHA256 hex signature over the sorted-key JSON of *data*."""
    payload = json.dumps(data, sort_keys=True, separators=(",", ":")).encode()
    return hmac.new(secret.encode(), payload, hashlib.sha256).hexdigest()


def encode_oauth_state(mode: str, user_id: str | None = None, *, secret: str = "") -> str:
    """Encode OAuth state as base64 JSON.

    When *secret* is provided, adds a random nonce and HMAC-SHA256 signature so
    the callback can verify the state was generated by this server (CSRF protection).
    """
    data: dict = {"mode": mode}
    if user_id:
        data["uid"] = user_id
    if secret:
        data["nonce"] = secrets.token_urlsafe(16)
        # Sign a snapshot of data *before* adding "sig" so the signed payload
        # contains exactly {mode, [uid], nonce} — no more, no less.
        # On decode, "sig" is popped before re-signing, reconstructing the same set.
        # IMPORTANT: do not add new fields to `data` after this line.
        data["sig"] = _hmac_sign({k: v for k, v in data.items()}, secret)
    return base64.urlsafe_b64encode(json.dumps(data).encode()).decode()


def decode_oauth_state(state: str | None, *, secret: str = "") -> dict:
    """Decode and verify OAuth state from base64 JSON.

    When *secret* is provided, verifies the HMAC-SHA256 signature and rejects
    missing, tampered, or unsigned states — returning ``{}`` on any failure so
    the caller's ``decoded.get("mode") != "login"`` check correctly rejects it.
    Without a *secret*, accepts any parseable state (no CSRF protection).
    """
    if not state:
        if secret:
            logger.warning("OAuth callback received no state — rejecting")
            return {}
        return {"mode": "login"}

    try:
        decoded: dict = json.loads(base64.urlsafe_b64decode(state.encode()).decode())
    except (ValueError, binascii.Error, UnicodeDecodeError, json.JSONDecodeError):
        return {}

    if not isinstance(decoded, dict):
        return {}

    if secret:
        sig = decoded.pop("sig", None)
        if not isinstance(sig, str) or not sig:
            logger.warning("OAuth state missing or malformed HMAC signature — rejecting")
            return {}
        expected = _hmac_sign(decoded, secret)
        if not hmac.compare_digest(sig, expected):
            logger.warning("OAuth state HMAC mismatch — possible CSRF attempt")
            return {}

    return decoded
