"""OAuth state helpers — HMAC-signed state encoding/decoding for CSRF protection.

User/identity creation has moved to ``services.identity_service.IdentityService``
which provides idempotent reauth handling and data-drift reconciliation. The old
``find_or_create_user`` helper has been removed; see migration 080 and the
project documentation for the new admission model.
"""

import base64
import binascii
import hashlib
import hmac
import json
import logging
import secrets

LOGGER: logging.Logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# OAuth state encoding with HMAC-SHA256 CSRF protection
# ---------------------------------------------------------------------------


def _hmac_sign(data: dict, secret: str) -> str:
    """Return HMAC-SHA256 hex signature over the sorted-key JSON of *data*."""
    payload = json.dumps(data, sort_keys=True, separators=(",", ":")).encode()
    return hmac.digest(secret.encode(), payload, hashlib.sha256).hex()


def encode_oauth_state(mode: str, user_id: str | None = None, *, secret: str = "") -> str:
    """Encode OAuth state as base64 JSON.

    When *secret* is provided, adds a random nonce and HMAC-SHA256 signature so
    the callback can verify the state was generated by this server (CSRF protection).
    """
    data: dict = {"mode": mode}
    if user_id:
        data["uid"] = user_id
    if secret:
        data["nonce"] = secrets.token_urlsafe(16)
        # Sign a snapshot of data *before* adding "sig" so the signed payload
        # contains exactly {mode, [uid], nonce} — no more, no less.
        # On decode, "sig" is popped before re-signing, reconstructing the same set.
        # IMPORTANT: do not add new fields to `data` after this line.
        data["sig"] = _hmac_sign({k: v for k, v in data.items()}, secret)
    return base64.urlsafe_b64encode(json.dumps(data).encode()).decode()


def decode_oauth_state(state: str | None, *, secret: str = "") -> dict:
    """Decode and verify OAuth state from base64 JSON.

    When *secret* is provided, verifies the HMAC-SHA256 signature and rejects
    missing, tampered, or unsigned states — returning ``{}`` on any failure so
    the caller's ``decoded.get("mode") != "login"`` check correctly rejects it.
    Without a *secret*, accepts any parseable state (no CSRF protection).
    """
    if not state:
        if secret:
            LOGGER.warning("OAuth callback received no state — rejecting")
            return {}
        return {"mode": "login"}

    try:
        decoded: dict = json.loads(base64.urlsafe_b64decode(state.encode()).decode())
    except (ValueError, binascii.Error, UnicodeDecodeError, json.JSONDecodeError):
        LOGGER.warning("OAuth state decode failed — malformed or tampered payload")
        return {}

    if not isinstance(decoded, dict):
        return {}

    if secret:
        sig = decoded.pop("sig", None)
        if not isinstance(sig, str) or not sig:
            LOGGER.warning("OAuth state missing or malformed HMAC signature — rejecting")
            return {}
        expected = _hmac_sign(decoded, secret)
        if not hmac.compare_digest(sig, expected):
            LOGGER.warning("OAuth state HMAC mismatch — possible CSRF attempt")
            return {}

    return decoded
