-- 055: Add activation_codes table + is_activated flag on users
--
-- activation_codes  – OTP codes generated by bot on niibot_auth redemption
-- users.is_activated – whether the user has activated their account

ALTER TABLE users ADD COLUMN IF NOT EXISTS is_activated BOOLEAN NOT NULL DEFAULT FALSE;

-- Existing OAuth accounts are trusted; only new signups require OTP activation.
UPDATE users SET is_activated = TRUE WHERE is_activated = FALSE;

CREATE TABLE IF NOT EXISTS activation_codes (
    code_hash        TEXT        PRIMARY KEY,  -- SHA-256 of the 6-digit OTP
    platform         TEXT        NOT NULL DEFAULT 'twitch',
    platform_user_id TEXT        NOT NULL,
    expires_at       TIMESTAMPTZ NOT NULL,
    used_at          TIMESTAMPTZ,
    used_by_user_id  UUID        REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_activation_codes_platform_user
    ON activation_codes(platform, platform_user_id);
