-- 089: activation_codes → grant model (lifecycle + provenance + monitoring).
--
-- ## Why
-- The activation code was doing three jobs badly:
--   1. Channel-points redeemers had to receive a whisper and re-type a 6-digit
--      code on /activate — a fragile conversion step for a value (the paid
--      channel-points toll) that is already captured at redemption time.
--   2. There was no record of a code's lifecycle. The admin view only listed
--      "unused, not expired" codes; issued / consumed / expired / revoked and
--      the redemption it came from were invisible.
--   3. Two write paths (redeem set users.is_activated; AdmissionService set
--      memberships) updated admission state in separate transactions.
--
-- ## Model after this migration
-- One row per *grant of the right to activate*, with a kind:
--   * channel_points — issued by the bot on a niibot_auth redemption. Carries
--     redemption_id / channel_id / reward_cost. Consumed automatically when the
--     same Twitch identity next logs in (no code entry, no whisper dependency).
--   * owner_manual   — issued by the owner from the admin panel. Bearer code:
--     not bound to an account, redeemed by typing it on /activate. TTL + single
--     use + revoke are the controls.
--
-- status: issued → consumed | expired | revoked  (terminal states kept for the
-- onboarding funnel; a daily loop marks expiry and scrubs old rows).
--
-- The table keeps its name (activation_codes) and the code_hash / code_plain
-- columns. What changes: a surrogate id PK (so historical rows can coexist
-- without 6-digit hash PK collisions), a partial-unique index enforcing one
-- live code per hash, and the provenance / lifecycle columns.

-- ============================================
-- 1. Surrogate PK — code_hash is no longer unique across history.
-- ============================================
ALTER TABLE activation_codes ADD COLUMN IF NOT EXISTS id BIGSERIAL;
ALTER TABLE activation_codes DROP CONSTRAINT IF EXISTS activation_codes_pkey;
ALTER TABLE activation_codes ADD PRIMARY KEY (id);

-- ============================================
-- 2. Provenance + lifecycle columns.
-- ============================================
ALTER TABLE activation_codes
    ADD COLUMN IF NOT EXISTS kind TEXT NOT NULL DEFAULT 'owner_manual'
        CHECK (kind IN ('channel_points', 'owner_manual')),
    ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'issued'
        CHECK (status IN ('issued', 'consumed', 'expired', 'revoked')),
    ADD COLUMN IF NOT EXISTS issued_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS issued_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS redemption_id TEXT,
    ADD COLUMN IF NOT EXISTS channel_id TEXT,
    ADD COLUMN IF NOT EXISTS reward_cost INT,
    ADD COLUMN IF NOT EXISTS attempt_count INT NOT NULL DEFAULT 0;

-- owner_manual codes are unbound at issue time; platform_user_id is filled in
-- when the code is redeemed. channel_points grants always know it upfront.
ALTER TABLE activation_codes ALTER COLUMN platform_user_id DROP NOT NULL;

-- ============================================
-- 3. Backfill existing rows.
--    Every existing code was generated by the bot's niibot_auth handler, i.e.
--    a channel-points grant. issued_at is unknown historically — estimate it
--    from the 72h TTL. channel_id is left NULL for historical rows.
-- ============================================
UPDATE activation_codes
   SET kind      = 'channel_points',
       issued_at = expires_at - INTERVAL '72 hours',
       status    = CASE
                     WHEN used_at IS NOT NULL   THEN 'consumed'
                     WHEN expires_at < NOW()    THEN 'expired'
                     ELSE 'issued'
                   END;

-- ============================================
-- 4. Indexes.
-- ============================================
-- One live code per hash (redeem / consume look up WHERE status = 'issued').
CREATE UNIQUE INDEX IF NOT EXISTS idx_activation_codes_hash_live
    ON activation_codes (code_hash) WHERE status = 'issued';

-- Funnel queries group by kind + status.
CREATE INDEX IF NOT EXISTS idx_activation_codes_kind_status
    ON activation_codes (kind, status);

-- Daily cleanup loop scans issued codes past expiry.
CREATE INDEX IF NOT EXISTS idx_activation_codes_live_expiry
    ON activation_codes (expires_at) WHERE status = 'issued';

-- Login path: "does this Twitch identity have an unconsumed channel-points grant?"
CREATE INDEX IF NOT EXISTS idx_activation_codes_pending_grant
    ON activation_codes (platform, platform_user_id)
    WHERE kind = 'channel_points' AND status = 'issued';
