#!/usr/bin/env bash
# Write the runtime env files on the deploy runner from GitHub Secrets/Variables.
#
# Replaces the hand-maintained heredoc block in .github/workflows/_deploy.yml.
# The key list, target files, conditionals and var defaults all come from
# env.manifest.json (generated by scripts/gen_env.py from env.registry.toml).
#
# Required env:
#   SECRETS_JSON        toJSON(secrets)  — { "NAME": "value", ... }
#   VARS_JSON           toJSON(vars)     — { "NAME": "value", ... }
#   PROJECT_DIR         repo checkout on the runner (manifest + output root)
#   DEPLOY_ENVIRONMENT  "production" | "staging"  (fallback for ENVIRONMENT)
# Optional env:
#   ENV_SUFFIX  ""  for prod, ".staging" for staging   (default "")
#   DRY_RUN     "1" prints each file to stdout instead of writing
#               (only ever run by hand with fake JSON — values are not redacted)
#
# Exits non-zero if a required secret (manifest.required_secrets) is missing.
set -euo pipefail

: "${SECRETS_JSON:?SECRETS_JSON is required (pass env: SECRETS_JSON: \${{ toJSON(secrets) }})}"
: "${VARS_JSON:?VARS_JSON is required (pass env: VARS_JSON: \${{ toJSON(vars) }})}"
: "${PROJECT_DIR:?PROJECT_DIR is required}"
: "${DEPLOY_ENVIRONMENT:?DEPLOY_ENVIRONMENT is required (production|staging)}"
ENV_SUFFIX="${ENV_SUFFIX:-}"
DRY_RUN="${DRY_RUN:-}"

export SECRETS_JSON VARS_JSON PROJECT_DIR DEPLOY_ENVIRONMENT ENV_SUFFIX DRY_RUN

python3 - <<'PYEOF'
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

project_dir = Path(os.environ["PROJECT_DIR"])
suffix = os.environ.get("ENV_SUFFIX", "")
deploy_env = os.environ["DEPLOY_ENVIRONMENT"].strip()
dry_run = os.environ.get("DRY_RUN") == "1"

manifest = json.loads((project_dir / "env.manifest.json").read_text(encoding="utf-8"))

# GitHub Secrets/Variables commonly carry a trailing newline (e.g. set from a
# file by .github/push.sh) — strip surrounding whitespace so it never lands in
# an env value. An interior newline is still rejected further down.
secrets = {k: str(v).strip() for k, v in json.loads(os.environ["SECRETS_JSON"] or "{}").items()}
gh_vars = {k: str(v).strip() for k, v in json.loads(os.environ["VARS_JSON"] or "{}").items()}

# manifest "file" tag -> path relative to PROJECT_DIR, with the env suffix applied.
# "shared" is special: backend/shared.staging.env, not backend/shared.env.staging.
FILE_PATHS = {
    "root": f".env{suffix}",
    "shared": f"backend/shared{suffix}.env",
    "api": f"backend/api/.env{suffix}",
    "twitch": f"backend/twitch/.env{suffix}",
    "discord": f"backend/discord/.env{suffix}",
}

# ── required secrets gate (replaces the old MISSING loop) ────────────────────
missing = [
    name
    for name in manifest.get("required_secrets", [])
    if not secrets.get(name, "").strip()
]
if missing:
    print(f"ERROR: missing required GitHub Secrets: {' '.join(missing)}", file=sys.stderr)
    print("Configure at: Settings -> Secrets and variables -> Actions", file=sys.stderr)
    sys.exit(1)

# ── derived: db_url ─────────────────────────────────────────────────────────
db_url = (
    manifest["db_url_template"]
    .replace("${POSTGRES_USER}", secrets.get("POSTGRES_USER", ""))
    .replace("${POSTGRES_PASSWORD}", secrets.get("POSTGRES_PASSWORD", ""))
    .replace("${POSTGRES_DB}", secrets.get("POSTGRES_DB", ""))
)


def resolve(key: str, spec: dict) -> str:
    source = spec["source"]
    if source == "derived:db_url":
        return db_url
    kind, _, name = source.partition(":")
    if kind == "secret":
        return secrets.get(name, "")
    # kind == "var"
    val = gh_vars.get(name, "")
    if val:
        return val
    if key == "ENVIRONMENT":
        return deploy_env
    return spec.get("default", "")


# ── build each file ────────────────────────────────────────────────────────
buffers: dict[str, list[str]] = {}
for key, spec in manifest["ci"].items():
    tag = spec.get("file")
    if not tag:  # runner-only (PROJECT_DIR, DEPLOY_WEBHOOK_URL, THREADS_SESSION_ID)
        continue
    if tag not in FILE_PATHS:
        print(f"ERROR: manifest ci[{key}].file={tag!r} has no known path", file=sys.stderr)
        sys.exit(1)
    value = resolve(key, spec)
    if spec.get("conditional") and not value:
        continue
    if "\n" in value or "\r" in value:
        print(f"ERROR: value for {key} contains a newline — refusing to write", file=sys.stderr)
        sys.exit(1)
    buffers.setdefault(tag, []).append(f"{key}={value}")

# Write every file, even with no keys — compose lists them under env_file: and
# a missing one aborts `docker compose up` (backend/twitch/.env has only the
# optional CONDUIT_ID). Matches the old heredoc, which always created all five.
for tag, path_rel in FILE_PATHS.items():
    lines = buffers.get(tag, [])
    content = "".join(f"{line}\n" for line in lines)
    if dry_run:
        print(f"\n===== {path_rel} =====")
        print(content, end="")
        continue
    target = project_dir / path_rel
    target.parent.mkdir(parents=True, exist_ok=True)
    # write_bytes (not write_text with newline=) — the newline kwarg is 3.10+
    # and the deploy runner's python3 is older; content is already \n-only.
    target.write_bytes(content.encode("utf-8"))
    print(f"wrote {path_rel} ({len(lines)} keys)")

if dry_run:
    print(f"\n(dry run - {deploy_env}, suffix {suffix!r}, no files written)")
PYEOF
