"""Bounded assistant harness shared by chat platforms."""

from shared.assistant.capacity import (
    AdmissionDecision,
    CapacityLease,
    ProviderBudgetPolicy,
    ProviderCapacityController,
    ProviderCapacitySnapshot,
    discord_free_tier_budgets,
    estimate_request_tokens,
    twitch_free_tier_budgets,
)
from shared.assistant.contracts import (
    AssistantOutcome,
    AssistantProvider,
    AssistantRequest,
    AssistantResult,
    AttemptRecord,
    FailureKind,
    InputSection,
    InputSectionKind,
    MessageRole,
    ProviderCompletion,
    ProviderFailure,
    ProviderMessage,
    ProviderRequest,
    ProviderResponse,
    TokenUsage,
)
from shared.assistant.harness import (
    AssistantHarness,
    HarnessResponse,
    build_assistant_harness,
)
from shared.assistant.health import primary_model_label
from shared.assistant.memory import (
    BoundedConversationMemoryStore,
    ConversationKey,
    ConversationMemoryStats,
    ConversationMemoryStore,
    ConversationTurn,
    NullConversationMemoryStore,
)
from shared.assistant.output import OutputPolicy, OutputProcessor, ProcessedOutput
from shared.assistant.prompt import PromptBudget, PromptCompiler
from shared.assistant.router import (
    BoundedAssistantRouter,
    CircuitState,
    ProviderCircuitSnapshot,
    RouterPolicy,
)

__all__ = [
    "AdmissionDecision",
    "AssistantOutcome",
    "AssistantHarness",
    "AssistantProvider",
    "AssistantRequest",
    "AssistantResult",
    "AttemptRecord",
    "BoundedAssistantRouter",
    "BoundedConversationMemoryStore",
    "CapacityLease",
    "CircuitState",
    "ConversationKey",
    "ConversationMemoryStats",
    "ConversationMemoryStore",
    "ConversationTurn",
    "FailureKind",
    "HarnessResponse",
    "InputSection",
    "InputSectionKind",
    "MessageRole",
    "NullConversationMemoryStore",
    "OutputPolicy",
    "OutputProcessor",
    "ProviderCompletion",
    "ProviderBudgetPolicy",
    "ProviderCapacityController",
    "ProviderCapacitySnapshot",
    "ProviderFailure",
    "ProviderMessage",
    "ProviderRequest",
    "ProviderResponse",
    "ProviderCircuitSnapshot",
    "ProcessedOutput",
    "PromptBudget",
    "PromptCompiler",
    "RouterPolicy",
    "TokenUsage",
    "build_assistant_harness",
    "discord_free_tier_budgets",
    "estimate_request_tokens",
    "primary_model_label",
    "twitch_free_tier_budgets",
]
