"""Deterministic Canon Role-play authoring and runtime preparation."""

from shared.roleplay.compiler import (
    MAX_CAPSULE_CHARS,
    MAX_COMPACT_CAPSULE_CHARS,
    ROLEPLAY_COMPILER_VERSION,
    canonical_roleplay_json,
    compile_roleplay_package,
    roleplay_content_digest,
)
from shared.roleplay.contracts import (
    CanonMode,
    ChannelStage,
    CharacterKnowledge,
    CharacterSheet,
    CompiledRoleplay,
    LoreEntry,
    Relationship,
    RelationshipState,
    ResolvedLore,
    RoleplayPackage,
    RoleplayRuntimeProfile,
    Scene,
    SourceKind,
    SpoilerPolicy,
    ValidationIssue,
    WorldSnapshot,
)
from shared.roleplay.evaluation import (
    EvaluationCase,
    EvaluationGrade,
    EvaluationRun,
    EvaluationSummary,
    EvaluationVariant,
    build_evaluation_request,
    grade_evaluation_output,
    summarize_evaluation_runs,
)
from shared.roleplay.prompt import build_roleplay_context_sections
from shared.roleplay.retrieval import resolve_lore
from shared.roleplay.validation import (
    MAX_EXAMPLE_REPLIES,
    MAX_LORE_ENTRIES,
    SUPPORTED_SCHEMA_VERSION,
    RoleplayValidationError,
    assert_valid_roleplay_package,
    validate_roleplay_package,
)

__all__ = [
    "MAX_CAPSULE_CHARS",
    "MAX_COMPACT_CAPSULE_CHARS",
    "ROLEPLAY_COMPILER_VERSION",
    "MAX_EXAMPLE_REPLIES",
    "MAX_LORE_ENTRIES",
    "SUPPORTED_SCHEMA_VERSION",
    "CanonMode",
    "ChannelStage",
    "CharacterKnowledge",
    "CharacterSheet",
    "CompiledRoleplay",
    "EvaluationCase",
    "EvaluationGrade",
    "EvaluationRun",
    "EvaluationSummary",
    "EvaluationVariant",
    "LoreEntry",
    "Relationship",
    "RelationshipState",
    "ResolvedLore",
    "RoleplayPackage",
    "RoleplayRuntimeProfile",
    "RoleplayValidationError",
    "Scene",
    "SourceKind",
    "SpoilerPolicy",
    "ValidationIssue",
    "WorldSnapshot",
    "assert_valid_roleplay_package",
    "build_evaluation_request",
    "build_roleplay_context_sections",
    "canonical_roleplay_json",
    "compile_roleplay_package",
    "grade_evaluation_output",
    "resolve_lore",
    "roleplay_content_digest",
    "summarize_evaluation_runs",
    "validate_roleplay_package",
]
